    Config:
      type: object
      required:
        - piid
        - pluginType
      properties:
        piid:
          type: string
          description: >-
            A string, unique to this deployment, used to identify this plugin in
            realtime
          example: pdspi-mapper-DOAC
        title:
          type: string
          description: Meaningful name for this plugin
          example: DOAC variable mapper
        enabled:
          type: boolean
          description: Admin can 'disable' this plugin, and if so, prevent it from being
          chosen on any client or dashboard.
          example: true 
        pluginDependencies:
          type: array
          items:
            type: string
            description: >-
              An array of container names upon which the plugin in question
              depends. For example, 'txscience/pds-fhir-example:0.2.0'. Mapper
              plugins must indicate a dependency on one or more FHIR plugins,
              but dependencies are discouraged otherwise in order to maintain
              the decoupling and reuse of plugins. Every plugin of type 'm' and
              'mD' must have at least one 'f' or 'fD' plugin listed in
              pluginDependencies, otherwise return 500.
        pluginType:
          type: string
          enum:
            - g
            - m
            - f
            - fD
            - mD
          description: >-
            A value identifying the plugin type. 
            'g'=Guidance, 'c'=Convenience, 'm'=Mapper, 'f'=FHIR, 'mD'= Default Mapper, 'fD'=Default FHIR. In 
            the clinical arena, only one FHIR server and only one mapper is 
            allowed, and this can be indicated either with the defaults, or by 
            only installing one mapper and one FHIR plugin type.
          example: m
        pluginTypeTitle:
          type: string
          enum:
            - Guidance
            - Mapper
            - FHIR
            - Default FHIR
            - Default Mapper
          description: >-
            A human-readable value for the type. 'g'=Guidance, 'c'=Convenience, 
            'm'=Mapper, 'f'=FHIR, 'mD'=Default Mapper, 'fD'=Default FHIR
        settingsDefaults:
          $ref: '#/components/schemas/Settings'
